site_name: TA Competency

theme:
  name: material
  palette:
    primary: deep blue
  features:
    - navigation.instant
    - navigation.indexes
    - content.code.annotate

nav: 
 - 主页:
   - index.md

 - 2024春 助教培训:
   - 2024S/index.md
   - 简要培训 常见误区与效率技巧:
     - 2024S/Intro_TricksAndTraps/index.md

 - 2023秋 助教培训:
   - textbook/index.md
   - 学生教评和课程调研: 
     - textbook/Evaluation&Survey/index.md
     - 教评打高分低分的原因: textbook/Evaluation&Survey/reasons_of_ratings.md
     - 15213课程目标中文版: textbook/Evaluation&Survey/15213.md
   - 如何出好编程作业: 
     - textbook/ProgrammingAssignment/index.md
     - attack lab 好在哪里: textbook/ProgrammingAssignment/attacklab.md
   - textbook/SupportLearning.md
   - textbook/recitation.md
   - 作业评分与查重:
      - textbook/Grading/index.md
      - 不同类型作业的评分: textbook/Grading/typeof_grading.md
      - 代码查重细节: textbook/Grading/plag_detect.md
 
 - 助教周刊Weekly(暂停更新):
   - weekly/index.md
   - weekly/20230605.md
   - weekly/20230612.md
   - weekly/20230619.md
   - weekly/20230626.md
   - weekly/20230703.md
   - weekly/20230710.md
   - weekly/20230717.md

 - 参考资料 reference:
   - reference/index.md
   - courses: reference/courses.md
   - resources: reference/resources.md


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
