site_name: TA Competency

theme:
  name: material
  palette:
    primary: deep blue
  features:
    - navigation.instant
    - navigation.indexes
    - content.code.annotate

nav: 
 - home:
   - index.md
 - 给计算机教师的教育学读本:
   - textbook/index.md
   - textbook/evaluation&survey.md

 - Weekly:
   - weekly/index.md
   - weekly/20230605.md
   - weekly/20230612.md
   - weekly/20230619.md
   - weekly/20230626.md
   - weekly/20230703.md
   - weekly/20230710.md

 - reference:
   - reference/index.md
   - courses: reference/courses.md
   - resources: reference/resources.md


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js